### PR TITLE
Fix some issues

### LINKED ISSUE #30: Wrong format in getting a value from config
https://github.com/kkrypt0nn/Python-Discord-Bot-Template/blob/0bd9008b9313f02baf127c74a1ba17aedc86bdbb/cogs/general.py#L130

the correct format should be `config['application_id']`

Besides the format the key value is also case sensitive

### LINKED ISSUE #32: DeprecationWarning: logout is deprecated, use Client.close instead
https://github.com/kkrypt0nn/Python-Discord-Bot-Template/blob/0bd9008b9313f02baf127c74a1ba17aedc86bdbb/cogs/owner.py#L30

we should remove this line

### LINKED ISSUE #34: Check if args is empty
https://github.com/kkrypt0nn/Python-Discord-Bot-Template/blob/0bd9008b9313f02baf127c74a1ba17aedc86bdbb/cogs/general.py#L141

The poll is created even if no arguments are passed.
Check if `args` is empty and display a message

### PR DESCRIPTION
**Pull request by anselal**
Closes #30
Closes #32
Closes #34

### CODE REVIEW

**Review by kkrypt0nn — CHANGES_REQUESTED** [review]
Also you can remove the field in the ping command and simply give the ms in the embed description, this will prevent multiple copies of something.

**Comment by kkrypt0nn** [comment]
You should try your changes before creating a pull request. Please fix what I mentioned.

**Comment by kkrypt0nn** [comment]
The ping embed will not work as you're missing an `,` after the color kwarg.

**Comment by anselal** [comment]
I prefer to add small messaged in embed to the description and leave the title empty, is that ok ?
Also, shall I add a color to the embed? Like error or warning ?

**Comment by kkrypt0nn** [comment]
> I prefer to add small messages in embeds to the description and leave the title empty, is that ok ?
> Also, shall I add a color to the embed? Like error or warning ?

You can keep the embed title to something like "Pong" and put the latency in the description.

**Comment by anselal** [comment]
Sorry about that. I meant if I shall add a color in the poll embed when there are no argument passed

**Comment by kkrypt0nn** [comment]
Yes, like other error embeds.

**Pull request closed without merging**
