### PR TITLE
Docs for Intents

### PR DESCRIPTION
**Pull request by Lost1419**
Just a few things like telling whats privileged and normal intents

### CODE REVIEW

**Comment by Lost1419** [comment]
Removed uneed things that where imported. Also using tasks now instead of sleeping

**Review by Lost1419 — COMMENTED** [review]
I think I have done all I can for today. Just a few changes of the code to check owner and maybe error handlers

**Comment by AstroOrbis** [comment]
Looks all good!

**Comment by kkrypt0nn** [comment]
Added the changes to the [version 2.1](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/releases/tag/2.1).

Thanks a lot!

**Pull request closed without merging**
