### PR TITLE
Add a "hackban" command

### PR DESCRIPTION
**Pull request by anselal**
ban a user by ID from a guild without him being in it

### CODE REVIEW

**Comment by anselal** [comment]
We can also add the user's thumbnail in the embed.

**Comment by anselal** [comment]
Now that I think of, we can merge ban and hackban.
`if member is None` then the user is not in the server and we can call `hackban`.
Do you prefer this approach ?

**Comment by anselal** [comment]
Just squash the commit when you merge the changes

**Comment by kkrypt0nn** [comment]
image

**Pull request closed without merging**
